name: Life in the Trees
favicon: null
layout_spectrum: 0.60993
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2b2b2b'
    - '#fcfcfc'
    - '#4e4e4e'
    - '#a4a4a4'
  brandStrength: 1
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
