name: Life in the Trees
favicon: null
layout_spectrum: 0.5714428431820124
typography_spectrum: 0.9711634046398103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121212'
    - '#bebebe'
    - '#484848'
    - '#757575'
    - '#a0a0a0'
  brandStrength: 1
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
